# Generated by Django 4.2.1 on 2023-06-01 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='img/')),
                ('img1', models.FileField(blank=True, null=True, upload_to='img/')),
                ('img2', models.FileField(blank=True, null=True, upload_to='img/')),
                ('img3', models.FileField(blank=True, null=True, upload_to='img/')),
                ('img4', models.FileField(blank=True, null=True, upload_to='img/')),
                ('img5', models.FileField(blank=True, null=True, upload_to='img/')),
                ('localisation', models.FileField(blank=True, null=True, upload_to='img/')),
                ('title', models.CharField(max_length=200)),
                ('is_sold', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('article_statu', models.CharField(choices=[('Disponible:', 'DISPONIBLE'), ('Vendu:', 'VENDU'), ('Nouveauté:', 'NOUVEAUTE'), ('Promotion:', 'PROMOTION'), ('Deuxieme Main:', 'DEUXIEME MAIN'), ('Reparer:', 'REPARER'), ('Tout risque', 'TOUT RISQUE'), ('Location:', 'LOCATION'), ('A louer:', 'A LOUER'), ('Troc ou Cash', 'TROC OU CASH')], max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('tag', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('Phone_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.category')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('items', models.ManyToManyField(to='product.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
